version: "3"
services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: "tuning-sql"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "rootpassword"
    ports:
      - "3306:3306"
    volumes:
      - "./mysqldata:/var/lib/mysql"
volumes:
  mysqldata:
